# Generated by Django 5.1.1 on 2026-02-05 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=10, verbose_name='ক্রমিক নং')),
                ('name', models.CharField(max_length=255, verbose_name='ভোটারের নাম')),
                ('voter_id', models.CharField(max_length=20, unique=True, verbose_name='ভোটার আইডি')),
                ('fathers_name', models.CharField(max_length=255, verbose_name='পিতার নাম')),
                ('mothers_name', models.CharField(max_length=255, verbose_name='মাতার নাম')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='পেশা')),
                ('dob', models.CharField(blank=True, max_length=20, null=True, verbose_name='জন্ম তারিখ')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('source_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='তথ্যের উৎস')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'ordering': ['serial'],
            },
        ),
    ]
