# Generated by Django 5.1.1 on 2026-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allvoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvoter',
            name='voter_id',
            field=models.CharField(max_length=20, verbose_name='ভোটার আইডি'),
        ),
    ]
